// Generated by scripts/generate-locales.js - do not edit
const locales = {};
locales['en'] = require('./en.json');
locales['es'] = require('./es.json');
locales['fr'] = require('./fr.json');
locales['de'] = require('./de.json');
locales['ja'] = require('./ja.json');
locales['zh'] = require('./zh.json');
module.exports = locales;
