'use strict';

const MAX_FUTURE_SKEW_MS = 5 * 60 * 1000;
const CONFIDENCE_RANK = { unknown: 0, heuristic: 1, trusted: 2, authoritative: 3, low: 0, medium: 1, high: 3 };
const SOURCE_RANK = { unknown: 0, github: 1, git: 2, 'workspace-fs': 3, 'native-fs': 4, fs: 3 };
function timestampOf(value) { if (value instanceof Date) return value.getTime(); if (typeof value === 'number') return value; if (typeof value === 'string' && value.trim()) { const n = Number(value); return Number.isFinite(n) ? n : Date.parse(value); } return NaN; }
function configValue(config, key, fallback) { try { return config?.get ? config.get(key, fallback) : fallback; } catch { return fallback; } }
function bucketFromAge(ageMs, thresholds = { nowMinutes: 60, todayHours: 24, twoDays: 2, oneWeek: 7 }) { if (!Number.isFinite(ageMs) || ageMs < 0) return 'unknown'; if (ageMs <= thresholds.nowMinutes * 60000) return 'now'; if (ageMs <= thresholds.todayHours * 3600000) return 'today'; if (ageMs <= thresholds.twoDays * 86400000) return '2d'; if (ageMs <= thresholds.oneWeek * 86400000) return '1w'; return 'stale'; }
function formatBadgeAge(bucket) { return ({ now: '!!', today: 'T', '2d': '2d', '1w': '1w', stale: '~~' })[bucket] || '?'; }
function formatBucketLabel(bucket) { return bucket || 'unknown'; }
function formatSourceLabel(source) { return ({ 'native-fs': 'Native filesystem', 'workspace-fs': 'Workspace filesystem', fs: 'Filesystem', git: 'Git', github: 'GitHub' })[source] || 'Unknown'; }
function formatBadge(bucket, source, config) { if (bucket === 'unknown' || source === 'unknown') return configValue(config, 'freshnessShowUnknown', true) ? '?' : null; return formatBadgeAge(bucket); }
function formatTooltip(freshness, config) { if (!freshness) return undefined; const verbosity = configValue(config, 'freshnessTooltipVerbosity', 'full'); const lines = [`Freshness: ${formatBucketLabel(freshness.bucket)}`]; if (freshness.exactTimestamp) lines.push(`Exact time: ${new Date(freshness.exactTimestamp).toISOString().replace('T', ' ').replace('Z', '')}`); lines.push(`Source: ${formatSourceLabel(freshness.source)}`, `Confidence: ${freshness.confidence}`); if (freshness.reason && verbosity !== 'minimal') lines.push(`Reason: ${freshness.reason}`); return lines.join('\n'); }
function unknown(reason, attempts = []) { return { timestamp: undefined, exactTimestamp: undefined, bucket: 'unknown', source: 'unknown', confidence: 'unknown', reasons: [reason], reason, attempts }; }
function result(timestamp, source, confidence, reason, config, extra = {}) { const bucket = bucketFromAge(Date.now() - timestamp); return { timestamp, exactTimestamp: timestamp, bucket, source, confidence, reasons: [reason], reason, ...extra }; }
function resolveFilesystem(uri, stat, now = Date.now(), config) { const timestamp = timestampOf(stat?.mtime); if (!Number.isFinite(timestamp)) return unknown('mtime-missing-or-invalid'); if (timestamp <= 0) return unknown('mtime-zero-or-negative'); if (timestamp > now + MAX_FUTURE_SKEW_MS) return unknown('mtime-implausibly-future'); const scheme = uri?.scheme || 'file'; const native = scheme === 'file' && stat?.__source === 'native-fs'; const trusted = stat?.__source === 'workspace-fs' || stat?.trusted === true || (scheme !== 'file' && configValue(config, 'freshnessAllowVirtualFs', false)); if (scheme !== 'file' && !trusted) return unknown('provider-metadata-untrusted'); const source = native ? 'native-fs' : 'workspace-fs'; return result(timestamp, source, native ? 'authoritative' : 'trusted', native ? 'compatible-file-native-stat' : 'workspace-fs-baseline', config); }
function githubContext(uri) { if (!uri) return null; const scheme = uri.scheme || ''; if (scheme !== 'github' && scheme !== 'vscode-vfs') return null; const segments = String(uri.path || '').replace(/^\/+/, '').split('/').filter(Boolean); if (segments.length < 3) return null; if (scheme === 'vscode-vfs' && !String(uri.authority || '').startsWith('github')) return null; let ref = 'HEAD'; const query = new URLSearchParams(uri.query || ''); ref = query.get('ref') || query.get('branch') || ref; const plus = String(uri.authority || '').indexOf('+'); if (scheme === 'vscode-vfs' && plus >= 0) { try { const json = JSON.parse(Buffer.from(String(uri.authority).slice(plus + 1), 'hex').toString('utf8')); ref = json?.ref?.id || ref; } catch {} } return { owner: segments[0], repo: segments[1], filePath: segments.slice(2).join('/'), ref }; }
async function resolveGithub(uri) { const parsed = githubContext(uri); if (!parsed) return { error: 'github-context-missing' }; if (typeof fetch !== 'function') return { error: 'github-fetch-unavailable' }; const url = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}/commits?path=${encodeURIComponent(parsed.filePath)}&sha=${encodeURIComponent(parsed.ref)}&per_page=1`; let response; try { response = await fetch(url, { headers: { Accept: 'application/vnd.github+json' } }); } catch (error) { return { error: `github-fetch-error:${error?.message || 'unknown'}` }; } if (!response?.ok) return { error: `github-http-${response?.status || 0}` }; let data; try { data = await response.json(); } catch { return { error: 'github-json-error' }; } const entry = Array.isArray(data) ? data[0] : null; const commit = entry?.commit; const timestamp = timestampOf(commit?.author?.date); if (!Number.isFinite(timestamp) || timestamp <= 0) return { error: 'github-no-timestamp' }; return { timestamp, author: commit?.author?.name || entry?.author?.login, message: commit?.message, url }; }
async function resolveFreshness({ uri, stat, provider, config, now = Date.now() } = {}) { const policy = configValue(config, 'freshnessSourcePolicy', 'auto'); const fs = resolveFilesystem(uri, stat, now, config); const attempts = [{ source: 'workspace-fs', reason: fs.reason || null }]; const fsUsable = Number.isFinite(fs.timestamp); if (fsUsable && policy !== 'git' && policy !== 'github') return { ...fs, attempts }; if (policy !== 'github' && policy !== 'unknown' && provider && typeof provider._getGitRecencyTimestamp === 'function') { try { const git = await provider._getGitRecencyTimestamp(uri); const timestamp = timestampOf(git?.timestampMs); if (Number.isFinite(timestamp) && timestamp > 0 && timestamp <= now + MAX_FUTURE_SKEW_MS) return { ...result(timestamp, 'git', 'heuristic', 'optional-git-enrichment', config, { author: git.author, message: git.message }), attempts: [...attempts, { source: 'git', reason: null }] }; attempts.push({ source: 'git', reason: git?.error || 'git-result-invalid' }); } catch (error) { attempts.push({ source: 'git', reason: `git-failure:${error?.message || 'unknown'}` }); } } if (policy !== 'git' && policy !== 'unknown') { const github = await resolveGithub(uri); attempts.push({ source: 'github', reason: github.error || null }); if (Number.isFinite(github.timestamp)) return { ...result(github.timestamp, 'github', 'heuristic', 'optional-github-enrichment', config, { author: github.author, message: github.message }), attempts }; } return fsUsable ? { ...fs, attempts } : unknown(fs.reason || 'no-trustworthy-source', attempts); }
function compareFreshness(a, b) { const c = (CONFIDENCE_RANK[a?.confidence] || 0) - (CONFIDENCE_RANK[b?.confidence] || 0); return c || (Number(a?.timestamp || a?.exactTimestamp || 0) - Number(b?.timestamp || b?.exactTimestamp || 0)); }
module.exports = { resolveFreshness, resolveFilesystem, timestampOf, MAX_FUTURE_SKEW_MS, compareFreshness, bucketFromAge, formatBadgeAge, formatBucketLabel, formatSourceLabel, formatBadge, formatTooltip, SOURCE_RANK, CONFIDENCE_RANK };
