#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const CSV_PATH = path.join(__dirname, '..', 'docs', 'translation-review.csv');
const OUT_DIR = path.join(__dirname, '..', 'src', 'locales');

function parseCsvLine(line) {
  const values = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      // handle escaped quotes ""
      if (inQuotes && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === ',' && !inQuotes) {
      values.push(cur);
      cur = '';
      continue;
    }
    cur += ch;
  }
  values.push(cur);
  return values;
}

async function main() {
  try {
    const csv = fs.readFileSync(CSV_PATH, 'utf8');
    const lines = csv.split(/\r?\n/).filter((l) => l.trim().length > 0);
    if (!lines.length) {
      console.error('No translation CSV content');
      process.exit(1);
    }

    const header = parseCsvLine(lines[0]);
    // header[0] should be 'key'
    const locales = header.slice(1).map((h) => h.trim()).filter(Boolean);
    if (!locales.length) {
      console.error('No locale columns in CSV');
      process.exit(1);
    }

    const accum = Object.create(null);
    for (const loc of locales) accum[loc] = Object.create(null);

    for (let i = 1; i < lines.length; i++) {
      const row = parseCsvLine(lines[i]);
      if (!row || row.length === 0) continue;
      // repair common malformed rows (missing one column) so generation is tolerant
      if (row.length !== header.length) {
        // heuristic: if exactly one column is missing and the last two parsed
        // values look like CJK (likely ja/zh), insert an empty `de` column at index 4
        if (row.length === header.length - 1) {
          const dePos = 4; // header index for 'de'
          // treat CJK / Japanese scripts (Hiragana/Katakana/Kanji) as indicators that
          // the de column was omitted and values have shifted left
          const cjkOrKana = /[\u3000-\u30FF\u4E00-\u9FFF\uFF00-\uFFEF]/;
          if (row[dePos] && row[dePos + 1]
              && cjkOrKana.test(row[dePos])
              && cjkOrKana.test(row[dePos + 1])) {
            console.warn(`Malformed CSV row ${i + 1}: missing 'de' column — auto-inserting empty value`);
            row.splice(dePos, 0, '');
          }
        }
        // if still short, pad with empty strings so indices align with header
        if (row.length < header.length) {
          while (row.length < header.length) row.push('');
        }
      }

      const key = row[0] && row[0].trim();
      if (!key) continue;
      for (let j = 1; j < header.length; j++) {
        const locale = header[j].trim();
        let value = row[j] !== undefined ? row[j] : '';
        value = value.replace(/\r|\n/g, '\\n');
        value = value.trim();
        // skip empty values
        if (!value) continue;
        accum[locale][key] = value;
      }
    }

    // ensure out dir
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const writtenLocales = [];
    for (const [loc, map] of Object.entries(accum)) {
      if (Object.keys(map).length === 0) continue;
      const outPath = path.join(OUT_DIR, `${loc}.json`);
      fs.writeFileSync(outPath, JSON.stringify(map, null, 2) + '\n', 'utf8');
      writtenLocales.push(loc);
      console.log(`Wrote ${outPath} (${Object.keys(map).length} keys)`);
    }

    // emit index file to make requires static & simple
    const indexPath = path.join(OUT_DIR, 'index.js');
    const indexLines = ["// Generated by scripts/generate-locales.js - do not edit",
      "const locales = {};"
    ];
    for (const loc of writtenLocales) {
      indexLines.push(`locales['${loc}'] = require('./${loc}.json');`);
    }
    indexLines.push('module.exports = locales;');
    fs.writeFileSync(indexPath, indexLines.join('\n') + '\n', 'utf8');
    console.log(`Wrote ${indexPath}`);
    process.exit(0);
  } catch (err) {
    console.error('Locale generation failed:', err);
    process.exit(1);
  }
}

if (require.main === module) main();
