const DEFAULT_CACHE_TIMEOUT = 120000; // 2 minutes
const DEFAULT_MAX_CACHE_SIZE = 10000;
const DEFAULT_PERSISTENT_CACHE_TTL = 24 * 60 * 60 * 1000; // 24 hours
const MAX_BADGE_LENGTH = 2;
const MONTH_ABBREVIATIONS = ['Ja', 'Fe', 'Mr', 'Ap', 'My', 'Jn', 'Jl', 'Au', 'Se', 'Oc', 'No', 'De'];
const DEFAULT_DECORATION_POOL_SIZE = Number(process.env.EXPLORER_DATES_DECORATION_POOL_SIZE || 2048);
const DEFAULT_FLYWEIGHT_CACHE_SIZE = Number(process.env.EXPLORER_DATES_FLYWEIGHT_CACHE_SIZE || 4096);
const WORKSPACE_SCALE_BALANCED_THRESHOLD = Number(
    process.env.EXPLORER_DATES_WORKSPACE_BALANCED_THRESHOLD || 15000
);
const WORKSPACE_SCALE_LARGE_THRESHOLD = Number(process.env.EXPLORER_DATES_WORKSPACE_LARGE_THRESHOLD || 250000);
const WORKSPACE_SCALE_EXTREME_THRESHOLD = Number(process.env.EXPLORER_DATES_WORKSPACE_EXTREME_THRESHOLD || 400000);
const WORKSPACE_SCAN_MAX_RESULTS = Number(
    process.env.EXPLORER_DATES_WORKSPACE_SCAN_MAX_RESULTS ||
    Math.min(WORKSPACE_SCALE_EXTREME_THRESHOLD + 1, 50001)
);

const GLOBAL_STATE_KEYS = {
    ADVANCED_CACHE: 'explorerDates.advancedCache',
    ADVANCED_CACHE_METADATA: 'explorerDates.advancedCacheMetadata',
    TEMPLATE_STORE: 'explorerDates.templates',
    WEB_GIT_NOTICE: 'explorerDates.webGitNotice'
};

// Shared keys used for web chunk registration. Avoid leading underscores so
// esbuild's property mangling does not rename them.
const WEB_CHUNK_GLOBAL_KEY = 'explorerDatesChunks';
const LEGACY_WEB_CHUNK_GLOBAL_KEY = '__explorerDatesChunks';

module.exports = {
    DEFAULT_CACHE_TIMEOUT,
    DEFAULT_MAX_CACHE_SIZE,
    DEFAULT_PERSISTENT_CACHE_TTL,
    DEFAULT_DECORATION_POOL_SIZE,
    DEFAULT_FLYWEIGHT_CACHE_SIZE,
    MAX_BADGE_LENGTH,
    MONTH_ABBREVIATIONS,
    WORKSPACE_SCALE_BALANCED_THRESHOLD,
    WORKSPACE_SCALE_LARGE_THRESHOLD,
    WORKSPACE_SCALE_EXTREME_THRESHOLD,
    WORKSPACE_SCAN_MAX_RESULTS,
    GLOBAL_STATE_KEYS,
    WEB_CHUNK_GLOBAL_KEY,
    LEGACY_WEB_CHUNK_GLOBAL_KEY
};
